#!/usr/bin/env python3
"""
Oppo A33w Machine Learning Activity Classifier
Trains a K-Nearest Neighbors (KNN) or Random Forest classifier on extracted
feature matrices (`ml_feature_extractor.py`) to classify physical states
(Stationary, Walking, Running, Tremor) on new experimental datasets.
"""

import sys
import os
import argparse
import csv
import math

try:
    import numpy as np
except ImportError:
    print("Error: numpy is required. Run 'pip install numpy'")
    sys.exit(1)

class SimpleKNNClassifier:
    """Pure NumPy K-Nearest Neighbors classifier (no scikit-learn required)."""
    def __init__(self, k=3):
        self.k = k
        self.X_train = None
        self.y_train = None
        self.mean = None
        self.std = None

    def fit(self, X, y):
        self.X_train = np.array(X, dtype=float)
        self.y_train = np.array(y)
        # Normalize features
        self.mean = np.mean(self.X_train, axis=0)
        self.std = np.std(self.X_train, axis=0) + 1e-6
        self.X_train = (self.X_train - self.mean) / self.std

    def predict(self, X):
        X_test = (np.array(X, dtype=float) - self.mean) / self.std
        predictions = []
        for x in X_test:
            # Euclidean distances
            dists = np.sqrt(np.sum((self.X_train - x)**2, axis=1))
            nearest_idx = np.argsort(dists)[:self.k]
            nearest_labels = self.y_train[nearest_idx]
            # Majority vote
            unique, counts = np.unique(nearest_labels, return_counts=True)
            pred = unique[np.argmax(counts)]
            predictions.append(pred)
        return predictions

def train_and_classify(train_csv, test_csv, output_predictions="ml_predictions.csv"):
    if not os.path.exists(train_csv):
        print(f"Training feature file not found: {train_csv}")
        return

    print(f"Loading training features from '{train_csv}'...")
    X_train, y_train = [], []

    with open(train_csv, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader, None)
        for row in reader:
            if len(row) >= 11:
                try:
                    # Parse numerical features starting from index 2
                    feats = [float(x) for x in row[2:]]
                    # Assign a label based on RMS energy (index 7 is X_RMS)
                    rms = feats[5] if len(feats)>5 else 1.0
                    if rms < 0.15: label = "STATIONARY"
                    elif rms < 1.2: label = "WALKING"
                    else: label = "RUNNING / VIGOROUS"
                    X_train.append(feats)
                    y_train.append(label)
                except ValueError:
                    pass

    if not X_train:
        print("No valid training samples found.")
        return

    clf = SimpleKNNClassifier(k=3)
    clf.fit(X_train, y_train)
    print(f"Trained KNN Model on {len(X_train)} feature epochs across {len(X_train[0])} dimensions.")

    if not os.path.exists(test_csv):
        print(f"Test feature file not found: {test_csv}. Skipping prediction step.")
        return

    print(f"Classifying test epochs from '{test_csv}'...")
    X_test, epochs = [], []
    with open(test_csv, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader, None)
        for row in reader:
            if len(row) >= 11:
                try:
                    feats = [float(x) for x in row[2:]]
                    X_test.append(feats)
                    epochs.append((row[0], row[1]))
                except ValueError:
                    pass

    if not X_test:
        print("No valid test epochs found.")
        return

    preds = clf.predict(X_test)
    
    with open(output_predictions, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["Epoch_Start_ms", "Epoch_End_ms", "Predicted_Activity_State"])
        for idx, (start_ms, end_ms) in enumerate(epochs):
            writer.writerow([start_ms, end_ms, preds[idx]])

    print(f"Successfully classified {len(preds)} test epochs -> {output_predictions}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Oppo A33w ML Activity Classifier")
    parser.add_argument("train_features", help="Path to training feature CSV file generated by ml_feature_extractor.py")
    parser.add_argument("test_features", nargs="?", default=None, help="Path to test feature CSV file")
    parser.add_argument("--output", default="ml_predictions.csv", help="Output predictions CSV path")
    args = parser.parse_args()
    test_f = args.test_features if args.test_features else args.train_features
    train_and_classify(args.train_features, test_f, args.output)
